/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chat_org_jni_JniLoader */

#ifndef _Included_com_chat_org_jni_JniLoader
#define _Included_com_chat_org_jni_JniLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chat_org_jni_JniLoader
 * Method:    getHelloStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chat_org_jni_JniLoader_getHelloStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
